[workspace]
members = [
    "bunyip-api",
    "bunyip-web",
    "crates/bunyip-domain",
    "crates/bunyip-oci",
    "crates/bunyip-oidc",
]
resolver = "2"

[workspace.package]
version = "0.9.0"
edition = "2021"
authors = ["PSA Systems"]
license = "MIT"
repository = "https://dev.a8n.run/psa-systems/bunyip"

[workspace.lints.clippy]
too_many_arguments = "allow"

[workspace.dependencies]
parking_lot = "0.12"
serde_json = "1"
tracing = "0.1"
thiserror = "1"
anyhow = "1"
rand = "0.8"
sha2 = "0.10"

[workspace.dependencies.tokio]
version = "1"
features = ["full"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]

[workspace.dependencies.uuid]
version = "1.11"
features = [
    "v4",
    "serde",
]

[workspace.dependencies.chrono]
version = "0.4"
features = ["serde"]

[workspace.dependencies.tracing-subscriber]
version = "0.3"
features = ["env-filter"]
